# cluster setting
cluster.name: "hb-es-cluster"
cluster.initial_master_nodes: ["hb-es-node1", "hb-es-node2", "hb-es-node3"]

# node name
node.name: "hb-es-node3"

# host network setting
network.host: 10.10.125.233
network.publish_host: 10.10.125.233
http.port: 9200
transport.tcp.port: 9300
transport.publish_port: 9300

# node attribute setting
node.master: true
node.data: true

# detail the private IPs of your nodes:
#discovery.zen.ping.unicast.hosts: ["10.10.125.231", "10.10.125.232", "10.10.125.233"]
discovery.seed_hosts: ["10.10.125.231:9300", "10.10.125.232:9300", "10.10.125.233:9300"]

# lock memory heap
bootstrap.memory_lock: true

# xpack setting
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12

