# cluster setting
cluster.name: "hb-es-cluster"
cluster.initial_master_nodes: ["hb-es-node1", "hb-es-node2", "hb-es-node3"]

# node name
node.name: "hb-es-node3"

# host network setting
network.host: 10.10.125.233

# node attribute setting
node.master: true
node.data: true

# detail the private IPs of your nodes:
#discovery.zen.ping.unicast.hosts: ["10.10.125.231", "10.10.125.232", "10.10.125.233"]
discovery.seed_hosts: ["10.10.125.231", "10.10.125.232", "10.10.125.233"]

# lock memory heap
bootstrap.memory_lock: true

# xpack setting
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
